---
apiVersion: v1
kind: ConfigMap
metadata:
  name: core-deployment-config
data:
  # Core configmap values that are independent for each deployment.
  # Commented out section below needs to be overwritten in kustomize overlay
  # Values of keys further down may differ from deployment, if so comment out here and add in deployments repo

  # AM_REALM: value_in_overlay
  # BASE_FQDN: value_in_overlay
  # CERT_ISSUER: value_in_overlay
  # IDENTITY_DEFAULT_USER_AUTHENTICATION_SERVICE: value_in_overlay
  # IDENTITY_GOOGLE_SECRET_STORE_NAME: value_in_overlay
  # IDENTITY_GOOGLE_SECRET_STORE_OAUTH2_CA_CERTS_SECRET_NAME: value_in_overlay
  # IDENTITY_PLATFORM_FQDN: value_in_overlay
  # IG_FQDN: value_in_overlay
  # MTLS_FQDN: value_in_overlay
  # OB_ASPSP_ORG_ID: value_in_overlay
  # USER_OBJECT: value_in_overlay

  # End of kustomize overlay


  # Environment Settings for SAPIG & Cloud Platform that do not change from deployment to deployment

  # Cloud
  # CDK value: (Cloud Developer's Kit) development identity platform
  # CDM value: CDM (Cloud Deployment Model)
  # FIDC value: FIDC (Forgerock Identity Cloud) identity cloud platform
  CLOUD_TYPE: "FIDC"
  # Connection settings for the IG hosted data repo
  GATEWAY_DATA_REPO_URI: "http://ig:80"
  # Enable Test Trusted Directory
  IG_TEST_DIRECTORY_ENABLED: "true"
  # Path to the IG truststore
  IG_TRUSTSTORE_PATH: "/secrets/truststore/igtruststore"
  # SAPIG
  # core: base sapig
  # ob: Open Banking specification of sapig
  SAPIG_TYPE: "core"