namespace: sandbox
commonLabels:
  app.kubernetes.io/name: "forgerock"
resources:
- securebanking
- kustomizeConfig
- ingress.yaml

patchesStrategicMerge:
  - secret.yaml
  - configmap.yaml
  - deployment.yaml

#images:
#- name: ig
#  newName: repo location
#  newTag: tag name