apiVersion: v1
kind: ConfigMap
metadata:
  name: ob-deployment-config
data:

  #IG_OB_ASPSP_SIGNING_KID: value_in_overlay
  #OB_ASPSP_SOFTWARE_ID: value_in_overlay
  #OB_ASPSP_ORG_ID: value_in_overlay

  # Name of the RS Service
  RS_INTERNAL_SVC: "test-facility-bank"
  # Name of the RCS Service
  RCS_API_INTERNAL_SVC: "remote-consent-service"
  # Name of the RCS UI Service
  RCS_UI_INTERNAL_SVC: "remote-consent-service-user-interface"
  # Connection Setting for the Remote Consent Service
  RCS_CONSENT_STORE_URI: "http://remote-consent-service:8080/consent/store"
  # RCS connection settings for the RS API
  RS_API_URI: "http://test-facility-bank:8080"
  # kid of the key used by RCS to sign Consent Response JWTs
  RCS_CONSENT_RESPONSE_JWT_SIGNINGKEYID: "rcs-jwt-signer"
  # iss claim value set by RCS in Consent Response JWTs
  RCS_CONSENT_RESPONSE_JWT_ISSUER: "secure-open-banking-rcs"
  # Path to the Open Banking signing key used by IG
  IG_OB_ASPSP_SIGNING_KEYSTORE_PATH: "/secrets/open-banking/ig-ob-signing-key.p12"
  # Keystore file type of IG_OB_ASPSP_SIGNING_KEYSTORE_PATH
  IG_OB_ASPSP_SIGNING_KEYSTORE_TYPE: "PKCS12"
  # Alias of the signing key within the IG_OB_ASPSP_SIGNING_KEYSTORE_PATH keystore
  IG_OB_ASPSP_SIGNING_KEYSTORE_ALIAS: "jwtsigner"