apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
  - name: testdirectory
    newName: europe-west4-docker.pkg.dev/sbat-gcr-develop/sapig-docker-artifact/securebanking/sapig-test-trusted-directory
    newTag: latest
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/name: forgerock
resources:
  - configmap.yaml
  - deployment.yaml
  - ingress.yaml
  - secret.yaml
  - service.yml