apiVersion: v2
name: secure-api-gateway-core
description: Helm chart for deploying the secure-api-gateway CORE edition to kubernetes cluster
type: application
version: 5.3.0
appVersion: 5.3.0

dependencies:
  - name: ig-fapi-pep-as
    version: 2026.6.0-20260629092452-2e6cded9f7e232b3a2762b2ac844c9f81df6e98f
    repository: "@forgerock-helm"
  - name: ig-fapi-pep-rs
    version: 2026.6.0-20260629092452-2e6cded9f7e232b3a2762b2ac844c9f81df6e98f
    repository: "@forgerock-helm"
  - name: sample-trusted-directory
    version: 2026.6.0-20260629092452-2e6cded9f7e232b3a2762b2ac844c9f81df6e98f
    repository: "@forgerock-helm"
    condition: test-trusted-directory.enabled
