---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ob-deployment-config
data:
  # OB configmap values that are independent for each deployment.
  # Commented out section below needs to be overwritten in kustomize overlay
  # Values of keys further down may differ from deployment, if so comment out here and add in deployments repo

  # IG_OB_ASPSP_SIGNING_KID: value_in_overlay
  # OB_ASPSP_ORG_ID: value_in_overlay
  # OB_ASPSP_SOFTWARE_ID: value_in_overlay

  # End of kustomize overlay


  # Environment Settings for SAPIG & Cloud Platform that do not change from deployment to deployment

  # Alias of the signing key within the IG_OB_ASPSP_SIGNING_KEYSTORE_PATH keystore
  IG_OB_ASPSP_SIGNING_KEYSTORE_ALIAS: "jwtsigner"
  # Path to the Open Banking signing key used by IG
  IG_OB_ASPSP_SIGNING_KEYSTORE_PATH: "/secrets/open-banking/ig-ob-signing-key.p12"
  # Keystore file type of IG_OB_ASPSP_SIGNING_KEYSTORE_PATH
  IG_OB_ASPSP_SIGNING_KEYSTORE_TYPE: "PKCS12"
  # Path to Test Trusted Directory keystore containing the CA cert
  IG_TEST_DIRECTORY_CA_KEYSTORE_PATH: "/secrets/test-trusted-directory/test-trusted-dir-keystore.p12"
  # Keystore file type of IG_TEST_DIRECTORY_CA_KEYSTORE_PATH
  IG_TEST_DIRECTORY_CA_KEYSTORE_TYPE: "PKCS12"
  # Alias of the Test Trusted Directory's CA cert within the IG_TEST_DIRECTORY_CA_KEYSTORE_PATH keystore
  IG_TEST_DIRECTORY_CA_KEYSTORE_ALIAS: "ca"
  # Alias of the Test Trusted Directory's signing cert within the IG_TEST_DIRECTORY_SIGNING_KEYSTORE_PATH keystore
  IG_TEST_DIRECTORY_SIGNING_KEYSTORE_ALIAS: "jwt-signer"
  # Path to Test Trusted Directory keystore containing the signing key
  IG_TEST_DIRECTORY_SIGNING_KEYSTORE_PATH: "/secrets/test-trusted-directory/test-trusted-dir-keystore.p12"
  # Keystore file type of IG_TEST_DIRECTORY_SIGNING_KEYSTORE_PATH
  IG_TEST_DIRECTORY_SIGNING_KEYSTORE_TYPE: "PKCS12"
  # Name of the RCS Service
  RCS_API_INTERNAL_SVC: "remote-consent-service"
  # iss claim value set by RCS in Consent Response JWTs
  RCS_CONSENT_RESPONSE_JWT_ISSUER: "secure-open-banking-rcs"
  # kid of the key used by RCS to sign Consent Response JWTs
  RCS_CONSENT_RESPONSE_JWT_SIGNINGKEYID: "rcs-jwt-signer"
  # Connection Setting for the Remote Consent Service
  RCS_CONSENT_STORE_URI: "http://remote-consent-service:8080/consent/store"
  # Name of the RCS UI Service
  RCS_UI_INTERNAL_SVC: "remote-consent-service-user-interface"
  # RCS connection settings for the RS API
  RS_API_URI: "http://test-facility-bank:8080"
  # Name of the RS Service
  RS_INTERNAL_SVC: "test-facility-bank"