namespace: dev
commonLabels:
  app.kubernetes.io/name: "forgerock"
resources:
- securebanking
- kustomizeConfig
- ingress.yaml

patchesStrategicMerge:
  - configmap.yaml
  - deployment.yaml
  - secret.yaml

# Commented out section below needs to be overwritten in kustomize overlay 

#images:
#- name: ig
#  newName: repo location
#  newTag: tag name