apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
`  - includeSelectors: true
    pairs:`
      app.kubernetes.io/name: sapig
resources:
  - configmap.yaml
  - deployment.yaml
  - ingress.yaml
  - secret.yaml
  - service.yml