- op: add
  path: "/spec/rules/0/http/paths/1"
  value:
    path: /rcs/api/
    pathType: Prefix
    backend: 
      service:
        name: ig
        port:
          number: 80
- op: add
  path: "/spec/rules/0/http/paths/2"
  value:
    path: /jwksproxy
    pathType: Prefix
    backend: 
      service:
        name: ig
        port:
          number: 80
- op: add
  path: "/spec/rules/0/http/paths/3"
  value:
    path: /rcs/ui/
    pathType: Prefix
    backend: 
      service:
        name: ig
        port:
          number: 80