#images:
#- name: ig
#  newName: repo location
#  newTag: tag name
namespace: sandbox
patches:
  - path: configmap.yaml
  - path: deployment.yaml
  - path: secret.yaml
resources:
  - ingress.yaml
  - securebanking