apiVersion: v1
kind: Secret
metadata:
  name: core-secrets
type: Opaque
data:
  # Commented out section below needs to be overwritten in kustomize overlay 

  # IG_AGENT_ID: value_in_overlay
  # IG_AGENT_PASSWORD: value_in_overlay
  # IG_CLIENT_ID: value_in_overlay
  # IG_CLIENT_SECRET: value_in_overlay
  # IG_IDM_PASSWORD: value_in_overlay
  # IG_IDM_USER: value_in_overlay
  # IG_METRICS_PASSWORD: value_in_overlay
  # IG_METRICS_USERNAME: value_in_overlay
  # IG_TRUSTSTORE_PASSWORD: value_in_overlay

  # End of kustomize overlay
